### ISSUE TITLE
coffiasd - createGauge is permissionless , allowing attackers to push numerous pools into the voter.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#101]
coffiasd

High

# createGauge is permissionless , allowing attackers to push numerous pools into the voter.

## Summary
[Voter.sol::createGauge](https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Voter.sol#L323-L378)  is permissionless , attackers to push numerous pools into the voter , result in  [Voter.sol::updateAll](https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Voter.sol#L509-L511) out of gas.

## Vulnerability Detail
From [Voter.sol::createGauge](https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Voter.sol#L349-L351) we can see
```solidity
  if (msg.sender != governor && msg.sender != emergencyCouncil) { // gov can create for any pool, even non-Velocimeter pairs
      require(isPair, "!_pool");
      require(IGaugePlugin(gaugePlugin).checkGaugeCreationAllowance(msg.sender, tokenA, tokenB), "!whitelistedForGaugeCreation");
  }
```

If current `msg.sender` is not governor and emergencyCouncil , protocol first check weather `pair` is created by `PairFactory.sol`. And then check `tokenA` and `tokenB` is WhitelistedForGaugeCreation.

[PairFactory.sol::createPair](https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/factories/PairFactory.sol#L108-L124) is also  permissionless anyone can call `createPair` to create a `pair`. The only check is that `tokenA` and `tokenB` pair is not exist.
[PairFactory.sol::createPair](https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/factories/PairFactory.sol#L111-L112)
```solidity
        require(token0 != address(0), 'ZA'); // Pair: ZERO_ADDRESS
        require(getPair[token0][token1][stable] == address(0), 'PE');
```

thus the last check and only check is [GaugePlugin.sol::checkGaugeCreationAllowance](https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/GaugePlugin.sol#L55-L63)
```solidity
  function checkGaugeCreationAllowance(
      address caller,
      address tokenA,
      address tokenB
  ) external view returns (bool) {
      return
          isWhitelistedForGaugeCreation[tokenA] ||
          isWhitelistedForGaugeCreation[tokenB];   <@
  }
```
From the code, we can see that `checkGaugeCreationAllowance` requires only one token that is `isWhitelistedForGaugeCreation`. An attacker can exploit this by using a single whitelisted token along with any other token to create numerous pools, overwhelming the voter system and potentially causing a denial of service (DoS).

test:
```solidity
  function testPermissionlessCreateGauge() public {
      address random = makeAddr("random");
      vm.startPrank(random);

      for(uint256 i;i<10;i++){
          MockERC20 tokenB = new MockERC20("name","symbol",18);
          address pair = factory.createPair(address(FLOW),address(tokenB),false);
          voter.createGauge(pair,0);
      }

      console2.log(voter.length());
  }
```
out:
```shell
Ran 1 test for test/Voter.t.sol:VoterTest
[PASS] testPermissionlessCreateGauge() (gas: 87659391)
Logs:
  10

Suite result: ok. 1 passed; 0 failed; 0 skipped; finished in 22.06ms (6.84ms CPU time)
```

## Impact
system dos

## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Voter.sol#L323-L378
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/GaugePlugin.sol#L55-L63

## Tool used

Manual Review

## Recommendation
```diff
@@ -58,8 +58,8 @@ contract GaugePlugin is IGaugePlugin, Ownable {
         address tokenB
     ) external view returns (bool) {
         return
-            isWhitelistedForGaugeCreation[tokenA] ||
-            isWhitelistedForGaugeCreation[tokenB];
+            isWhitelistedForGaugeCreation[tokenA] &&
+            isWhitelistedForGaugeCreation[tokenB]; //@audit & ?
     }
```

**Comment by nevillehuang** [comment]
Invalid, permisionless gauge creations with a single sided whitelisted token is intended per contest details (emphasis on `whitelisted tokens on one side`).  This also fails to identify a correct impact presented by issues #23 and #24

> Any users can create gauge for pools with whitelisted tokens on one side. (Permissionless gauge creation) Otherwise, gauge for pools without whitelisted tokens can only be created by protocol.

**Comment by coffiasd** [comment]
Escalate

@nevillehuang  The protocol indeed has a whitelist restriction, but please note the error I mentioned in my recommendation. Due to the whitelist's condition using '||' (OR) instead of '&&' (AND), this means that only one token needs to be in the whitelist to pass this whitelist check. As a result, the second token can be any custom token. This leads to a problem where players can add an unlimited number of elements to the list because users can customize the second token that is not in the whitelist

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> @nevillehuang  The protocol indeed has a whitelist restriction, but please note the error I mentioned in my recommendation. Due to the whitelist's condition using '||' (OR) instead of '&&' (AND), this means that only one token needs to be in the whitelist to pass this whitelist check. As a result, the second token can be any custom token. This leads to a problem where players can add an unlimited number of elements to the list because users can customize the second token that is not in the whitelist

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
This is a duplicate of #24, but has a very poorly described attack path/impact described. Will let HoJ decide

 - What DoS is this talking about?
 - Overwhelm what voter system? How does it relate to the protocol? Users can simply not vote for such gauges? Imo the described impact is a front-end issue.
> An attacker can exploit this by using a single whitelisted token along with any other token to create numerous pools, overwhelming the voter system and potentially causing a denial of service (DoS).


because of the lack of details of a valid attack path/protocol specific impact, I stand by my decision to invalidate

**Comment by coffiasd** [comment]
> This is a duplicate of #24, but has a very poorly described attack path/impact described. Will let HoJ decide
> 
> * What DoS is this talking about?
> * Overwhelm what voter system? How does it relate to the protocol?
> 
> > An attacker can exploit this by using a single whitelisted token along with any other token to create numerous pools, overwhelming the voter system and potentially causing a denial of service (DoS).
> 
> So I stand by the decision to invalidate

So if it's supported for me i leave comment on #24 instead of this

**Comment by nevillehuang** [comment]
@coffiasd You can leave your escalation here no problem, my argument is to keep invalid, but I will let hoj decide.

**Comment by coffiasd** [comment]
Alright, my point is that the current single whitelist restriction clearly allows suspicious actors to add any token to the list, bypassing the whitelist, which results in the whitelist not serving its intended purpose. Furthermore, Voter.sol::updateAll loops through this list. If too many tokens are added, there's a risk of running out of gas (OOG)

loop pool list:
```solidity
  function updateForRange(uint start, uint end) public {
      for (uint i = start; i < end; i++) {
          _updateFor(gauges[pools[i]]);
      }
  }

  function updateAll() external {
      updateForRange(0, pools.length);
  }
```

**Comment by nevillehuang** [comment]
@coffiasd 

- From my understanding , escalations is not for watsons to add on new impacts they didn’t previously mentioned
- oos gas issues require an explicit poc to prove impact per sherlock rules

**Comment by coffiasd** [comment]
add following test to Voter.t.sol
```solidity
    function testPermissionlessCreateGauge() public {
        FLOW.setMinter(address(minter));
        minter.startActivePeriod();
        voter.distribute();
    
        skip(30 days);

        //get voting power.
        flowDaiPair.approve(address(escrow), 5e17);
        uint256 tokenId = escrow.create_lock_for(1e16, FIFTY_TWO_WEEKS,address(owner));

        address random = makeAddr("random");
        vm.startPrank(random);

        address[] memory votePools = new address[](100);
        uint256[] memory weight = new uint256[](100);

        for(uint256 i;i<100;i++){
            MockERC20 tokenB = new MockERC20("name","symbol",18);
            address pair = factory.createPair(address(FLOW),address(tokenB),false);
            votePools[i] = pair;
            weight[i] = 1;
            voter.createGauge(pair,0);
        }

        //vote.
        vm.stopPrank();
        vm.prank(address(owner));
        voter.vote(tokenId,votePools,weight);

        skip(30 days);

        uint256 initialGas = gasleft();
        voter.distribute();
        uint256 gasUsed = initialGas - gasleft();

        console2.log("distribute cost gas:",gasUsed);
    }
```

```shell
distribute cost gas: 18390890
Suite result: ok. 1 passed; 0 failed; 0 skipped; finished in 70.93ms (63.80ms CPU time)
```

As data continues to fill up and unrestricted additions are made, the `updateFor` and `distribute` functions will eventually exceed the maximum gas limit. Please note that `updateAll` and `distribute` in the system both require looping through the entire pool list, and we have no way to remove elements from the system. Therefore, I believe this will be problematic and should be considered a valid issue.

**Comment by nevillehuang** [comment]
@coffiasd Nice PoC, would have been great in your original submission…although I am unsure if no way to remove gauge is correct given admins can kill gauges

**Comment by coffiasd** [comment]
kill gauges only delete the relationship bwt gauges and _pool , not pop the pool out of the pools list
```solidity
        delete isAlive[_gauge];
        delete external_bribes[_gauge];
        delete poolForGauge[_gauge];
        delete isGauge[_gauge];
        delete claimable[_gauge];
        delete supplyIndex[_gauge];
        delete gauges[_pool];
```

however both `updateFor` and `distribute` will loop pools list 

`updateAll`
```solidity
    function updateAll() external {
        updateForRange(0, pools.length);
    }
```

`distribute`
```solidity
    function distribute() external {
        distribute(0, pools.length);
    }
```

there is no way to pop pool out of pools list

**Comment by 0xklapouchy** [comment]
@nevillehuang 
The issue here is only about DoS in the updateAll() and distribute() functions. Both are mitigated by the `distribute(uint start, uint finish)`, `distribute(address[] memory _gauges)`, and `updateForRange(uint start, uint end)`, `updateFor(address[] memory _gauges)`, `updateGauge(address _gauge)`

**Comment by coffiasd** [comment]
according to paltform role:
>Out of Gas: Issues that result in Out of Gas errors either by the malicious user filling up the arrays or there is a practical call flow that results in OOG can be considered a valid medium or in cases of blocking all user funds forever maybe a valid high. Exception: In case the array length is controlled by the trusted admin/owner or the issue describes an impractical usage of parameters to reach OOG state then these submissions would be considered as low

basiclly, the length of pools can't be decreased by the trusted admin/owner 

Indeed, the issues can be mitigated by updating tokens individually. However, it's an undeniable fact that the updateAll() and distribute() functions still pose a risk of denial-of-service (DoS) attacks. We can't ignore this DoS risk just because mitigation is possible through individual updates. Unless these two functions are no longer used - and if they're not being used, why do they exist in the contract?

Furthermore, if an upgradeable contract can resolve existing issues through upgrades, does this mean there's no need to audit such contracts? Because all problems could theoretically be solved through upgrades

**Comment by nevillehuang** [comment]
Per comments [here](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/101#issuecomment-2283747685) and [here](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/101#issuecomment-2287166638), I believe this issue should be invalid

**Comment by coffiasd** [comment]
- This is a gradual but inevitable problem. While it may not cause immediate issues, it will eventually lead to system-wide problems as the number of pools grows
- Although workarounds exist (such as using ranged updates), the presence of potentially unusable functions is a design flaw that could lead to confusion or errors among users and developers

**Comment by cvetanovv** [comment]
It was not clear to me whether the admin can prevent this DoS?

**Comment by coffiasd** [comment]
> It was not clear to me whether the admin can prevent this DoS?

let me summarize it, first admin can't prevent this DOS , this DoS attack has the potential to break core functionality of the protocol , however according to @0xklapouchy 's point, admin can prevent this DoS by not use  `updateAll ` and `distribute` , instead of it admin invoke `distribute(uint start, uint finish)`, `distribute(address[] memory _gauges)`, and `updateForRange(uint start, uint end)`, `updateFor(address[] memory _gauges), updateGauge(address _gauge)`

**Comment by cvetanovv** [comment]
If the admin can prevent DoS, then this issue is invalid. The document states that the admin makes the right decisions: https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid

Planning to reject the escalation and leave the issue as is.

**Comment by coffiasd** [comment]
> If the admin can prevent DoS, then this issue is invalid. The document states that the admin makes the right decisions: https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid
> 
> Planning to reject the escalation and leave the issue as is.

Can you explain in detail which specific rule you're basing this on , `Admin Input/call validation` ? I don't believe the admin can prevent this DoS. If not using these methods that can lead to DoS is considered preventing DoS, I think that's unreasonable

please check this document:
https://docs.sherlock.xyz/audits/judging/judging#viii.-list-of-issue-categories-that-are-considered-valid
>Out of Gas: Issues that result in Out of Gas errors either by the malicious user filling up the arrays or there is a practical call flow that results in OOG can be considered a valid medium or in cases of blocking all user funds forever maybe a valid high

**Comment by nevillehuang** [comment]
Per @0xklapouchy comments,
- Core contract functionality of distribution of rewards is not broken given there are gauge specific distribution functionalities available as seen [here](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/Voter.sol#L572-L582), which is in fact the one called when claiming rewards as seen [here](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/GaugeV4.sol#L269-L272) i.e. distribution can be performed without looping through ALL gauges.
- Same argument can be applied for gauge updates as seen [here](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/Voter.sol#L497-L507)

so TLDR, I believe low severity is appropriate and hence invalid due to severity

**Comment by coffiasd** [comment]
```solidity
  function updateForRange(uint start, uint end) public {
      for (uint i = start; i < end; i++) {
          _updateFor(gauges[pools[i]]);
      }
  }
```
I believe that at least for the `updateForRange`  with start and end, it's uncontrollable. Why assume we need to update the first and last elements? Theoretically, many invalid elements could be inserted in the middle, so it's impossible to achieve the effect of updateAll in a single update, isn't it?

**Comment by nevillehuang** [comment]
Yes there is an inconsistency, but the distribution and updates for specific gauges will be invoked weekly as long as rewards are claimed, so core functionality is not broken + we can just split calls to updates/distribution if required. So at worse case it is a waste of gas for the honest gauges deployed.

So again, there is a workaround, and the core contract functionality of distribution and gauge updates is not broken.

**Comment by coffiasd** [comment]
check this funtion
```solidity
  function distribute(address[] memory _gauges) external {
      for (uint x = 0; x < _gauges.length; x++) {
          distribute(_gauges[x]);
      }
  }
```
I think your viewpoint is based on an assumption that the gauge list is fixed and known. However, in the gauge contract, anyone can [deposit](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/GaugeV4.sol#L439-L441) reward tokens, which may lead to the possibility that some gauges with rewards are not updated. Therefore, updating based on a fixed list of gauges is unreasonable.
I believe that in certain situations, a complete update is necessary

**Comment by cvetanovv** [comment]
@coffiasd 
> Can you explain in detail which specific rule you're basing this on , `Admin Input/call validation` ? I don't believe the admin can prevent this DoS. If not using these methods that can lead to DoS is considered preventing DoS, I think that's unreasonable

In my first comment, I asked if the admin could eventually prevent DoS. You answered me ambiguously:
> let me summarize it, first admin can't prevent this DOS , this DoS attack has the potential to break core functionality of the protocol , however according to @0xklapouchy 's point, admin can prevent this DoS by not use updateAll  and distribute

DoS can be prevented if the admin does not use these functions. But if they are not used because of that, then maybe we can say that they don't work and maybe this issue is Medium severity.

**Comment by nevillehuang** [comment]
I’m not sure I get your point. It is true we can possibly not invoke updates/distribution to all gauges at one shot with the DoSed functionality we slam gauge creations, but since we have the alternative of updating/distributing gauges specifically, I don’t see the broken functionality other than the fact that u are also assuming those specific gauges wont be updated/distributed? 

For context this functionalities that invoke distribution/updates for all gauges are only called externally, and not invoked elsewhere in the protocol, so when user claim rewards for specific gauges there will be no issue. I also want to reiterate the fact that this was explicitly noted as a design decision in the contest READ.ME per my comments [here](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/101#issuecomment-2274002543). This also ties back to why I believe #23 and #24 can be invalid/low severity as well, since admins can pause/kill any malicious gauges at anytime, they can intervene with spammed gauges and there will be no rewards farmed if so

**Comment by coffiasd** [comment]
@cvetanovv  @nevillehuang 
I think this submission is not a dup with #23 and #24 , so compare this issue with those two make no sence.

Your point about why this issue is invalid is that, rather than invoking the DoSed functionality, we instead call the following two functions:

```solidity
function updateForRange(uint start, uint end) public {
    for (uint i = start; i < end; i++) {
        _updateFor(gauges[pools[i]]);
    }
}
```

```solidity
  function distribute(address[] memory _gauges) external {
      for (uint x = 0; x < _gauges.length; x++) {
          distribute(_gauges[x]);
      }
  }
```
[1](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/101#issuecomment-2294835005)
[2](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/101#issuecomment-2294839353)
Please refer to the two explanations I provided above to understand why they cannot achieve the same effect.

In summary, the admin can't prevent the DoS, and the alternative functions mentioned cannot achieve the same effect

**Comment by nevillehuang** [comment]
I don’t seem to get your explanation at all honestly. If update/distribution of **specific** gauges is possible, what exactly is broken here? Yes I acknowledge the inconsistency DoSing updating/distributing all gauges functionality, but this does not break the core functionality as stated above.

I will let HoJ handle this, since we can’t seem to get through to each other and it will be a disservice to both of us in continuing this discussion.

**Comment by coffiasd** [comment]
I'll leave a final comment and let HoJ handle this. I don't mean to hurt anyone's feelings; I'm just standing by my point.

It seems you’ve already acknowledged that `updateForRange` is inconsistent.

And you suggest that we can use `distribute(address[] memory _gauges)` instead, but I disagree. We can't obtain a fixed list of gauges, as any gauge may have rewards deposited at any time. The deposits are permissionless.

**Comment by nevillehuang** [comment]
Don’t worry you have not hurt my feelings in anyway, it is just necessary discussion. Though till now, I still don’t get your point. 

@dawiddrzala maybe you would want to take a look at this full discussion and consider if this is an issue? I have no clue what the watson meant by we cannot get a “fixed list of gauges”?? Maybe you can help shed some light

**Comment by dawiddrzala** [comment]
it could be the low issue, as there is nothing broken on the end, just one function is not going to work, but all of other can be called without any issues, that can happen as well with normal usage ( our apis have the list of all of the gauges so that is not problem for us ), or we can just use the index one in batches

**Comment by coffiasd** [comment]
At least we've reached one consensus: `one function is not going to work`. You mentioned, "we have the list of all of the gauges," but due to the permissionless nature of the system, we can't guarantee that this list won't exceed a certain length limit. This could lead to an out-of-gas error, even if we don't update all the gauges. Unless you manually selecting the gauges that you think need to be updated from the full list, ignoring others—even if they may have rewards token.

**Comment by dawiddrzala** [comment]
gauges also auto distribute if any user claim rewards from them, range function not require list of the gauges just end and start indexes

**Comment by coffiasd** [comment]
[For the start and end index i have already explained this once before，and I don't want to repeat myself](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/101#issuecomment-2294835005)

@cvetanovv @nevillehuang @dawiddrzala 
I think we have provided enough content and viewpoints. Regardless of who does it, please draw a final conclusion based on the arguments above. There's no need to waste anyone's time further. Thank you for everyone's participation

**Comment by cvetanovv** [comment]
I agree with the sponsor that this is а Low severity issue.

The issue itself is about DoS, not that a function doesn't work. Because of that, we have to look at whether there is a DoS on the protocol and not whether the function works.

The most important thing is that the admin can avoid this DoS by not using the function.

But even if we consider that a function won't work, we don't have broken functionality in the contract.

Planning to reject the escalation and leave the issue as is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [coffiasd](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/101/#issuecomment-2283695891): rejected
