### ISSUE TITLE
tvdung94 - Users will have to pay more than max payment amount when exercising ve (or lp) in some certain cases

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#188]
tvdung94

Medium

# Users will have to pay more than max payment amount when exercising ve (or lp) in some certain cases

## Summary
Max payment amount is one of input parameters of exercising functions, stating the max amount that a user is willing to pay. If the total amount exceeds this max amount, transactions will revert.

The problem is that the check for maximum payment amount is incorrect for exercisingVe and exercisingLp, making users pay more than maximum amount in some certain cases.
 
## Vulnerability Detail
The total amount users have to pay/transfer is `paymentAmountToAddLiquidity + paymentAmount`:

```solidity
uint256 paymentGaugeRewardAmount = _discount == 0 ? 0 : _takeFees(
            paymentToken,
            paymentAmount
        );
        _safeTransferFrom(
            paymentToken,
            msg.sender,
            address(this),
            paymentGaugeRewardAmount + paymentAmountToAddLiquidity
        );

```

when calculating actual payment amount for exercising ve/lp, the check does not take `paymentAmountToAddLiquidity`, which also contributes to the total amount users will have to pay besides `paymentAmount` , into account. Thus, sometimes users will have to pay more than the maximum payment amount that they agree to pay.

```solidity
if (paymentAmount > _maxPaymentAmount)
            revert OptionToken_SlippageTooHigh();
```

## Impact
Users have to pay more than intended, meaning users lose some extra amount of their funds
## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L612-L621

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L608-L609

## Tool used

Manual Review

## Recommendation
Consider including `paymentAmountToAddLiquidity` into the check
```solidity
if (paymentAmoun + paymentAmountToAddLiquidity > _maxPaymentAmount)
            revert OptionToken_SlippageTooHigh();
```

Duplicate of #199

**Comment by nevillehuang** [comment]
request poc

Need a more detailed analysis and/or PoC

**Comment by sherlock-admin4** [comment]
PoC requested from @sota1994

Requests remaining: **21**

**Comment by sota1994** [comment]
Hi,
My point is that users do not have slippage protection for the final amount they have to pay, since they have no control over the amount of liquidity of payment token they will have to pay (`paymentAmountToAddLiquidity`) for LP shares when exercising lp/ve. The current check only considers the discount payment amount equivalent to flow value, which is only one token of the pair. 

`paymentAmountToAddLiquidity` can fluctuate sharply because slippage control is not set for addLiquidity(). It can become quite huge when liquidity is low. Users have no control over both the amount of payment token for adding liquidity and the amount of LP shares they will receive, which might be undesirable.
There is a report confirmed by sponsor mentioning this behavior: https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/199

Even when slippage is set for `paymentAmountToAddLiquidity`, there is no guarantee that users are satisfied with the final payment amounts (`paymentAmountToAddLiquidity + paymentAmount`). 

POC
There is another report describing same issue with POC implemented: https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/328
