### ISSUE TITLE
Sentryx - Gauge's reward rate and period duration can be griefed

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#259]
Sentryx

Medium

# Gauge's reward rate and period duration can be griefed

## Summary
Anybody can send reward tokens to a gauge via `notifyRewardAmount()` when there're little rewards left or when the current period finish has ended and extend the reward period by another week and dilute the reward rate.
## Vulnerability Detail
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/GaugeV4.sol#L563-L599
```solidity
    function notifyRewardAmount(address token, uint amount) external lock {
        require(token != stake);
        require(amount > 0);
        if (!isReward[token]) {
            require(IVoter(voter).isWhitelisted(token), "rewards tokens must be whitelisted");
            require(rewards.length < MAX_REWARD_TOKENS, "too many rewards tokens");
        }
        if (rewardRate[token] == 0) _writeRewardPerTokenCheckpoint(token, 0, block.timestamp);
        (rewardPerTokenStored[token], lastUpdateTime[token]) = _updateRewardPerToken(token, type(uint).max, true);

        if (block.timestamp >= periodFinish[token]) {
            uint256 balanceBefore = IERC20(token).balanceOf(address(this));
            _safeTransferFrom(token, msg.sender, address(this), amount);
            uint256 balanceAfter = IERC20(token).balanceOf(address(this));
            amount = balanceAfter - balanceBefore;
            rewardRate[token] = amount / DURATION;
        } else {
            uint _remaining = periodFinish[token] - block.timestamp;
            uint _left = _remaining * rewardRate[token];
            require(amount > _left); 
            uint256 balanceBefore = IERC20(token).balanceOf(address(this));
            _safeTransferFrom(token, msg.sender, address(this), amount);
            uint256 balanceAfter = IERC20(token).balanceOf(address(this));
            amount = balanceAfter - balanceBefore;
            rewardRate[token] = (amount + _left) / DURATION;
        }
        require(rewardRate[token] > 0);
        uint balance = IERC20(token).balanceOf(address(this));
        require(rewardRate[token] <= balance / DURATION, "Provided reward too high");
        periodFinish[token] = block.timestamp + DURATION;
        if (!isReward[token]) {
            isReward[token] = true;
            rewards.push(token);
        }

        emit NotifyReward(msg.sender, token, amount);
    }
```

Whether the current period has finished or not, anybody can deposit rewards to a gauge and dilute the reward rate and extend the period finish time.
## Impact
Diluted reward rate for current stakers in the gauge. Also extended waiting times for current period to finish. 
## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/GaugeV4.sol#L563-L599
## Tool used
Manual Review
## Recommendation
Consider implementing validation to ensure that this function is callable by anyone only if the previous reward period has already expired. Otherwise, when there is an active reward period, it may only be called by the designated reward distributor account.

**Comment by nevillehuang** [comment]
request poc

Could be invalid, no loss of funds since the rewards are simply delayed and can be retrieve in subsequent epochs. Normally this kind of synthethix style reward staking have notification of rewards permissioned

**Comment by sherlock-admin3** [comment]
PoC requested from @Sentryx

Requests remaining: **32**

**Comment by flackoon** [comment]
Hey @nevillehuang,
We are currently unable to provide a PoC due to being engaged in another audit. Apart from 12 other watsons pointing out the same issue, we can provide a [link](https://github.com/code-423n4/2022-05-velodrome-findings/issues/172) to the same finding from another audit. The issue is widely recognized so we won't get into explanatory mode 😅 We believe it's a valid medium, but we are currently not able to further defend it. If any other watson is willing to escalate or step in, it'd be much appreciated.

**Comment by nevillehuang** [comment]
Will keep medium since it can cause loss of yield by delaying rewards for more than a week, so it is effectively DoS meeting sherlocks guidelines

**Comment by dawiddrzala** [comment]
not valid you need to provide at least the same amount of rewards that is currently left to distribut in the gauge  require(amount > _left);  which make it not possible to ddos

**Comment by nevillehuang** [comment]
@dawiddrzala I believe this issue is valid, because `notifyRewardAmount ` is permisionless, and is not only able to be called via the `Voter.sol`. Your above comment is correct if the `notifyRewardAmount ` would have been gated to only be able to be called by the `Voter.distribute()`.

**Comment by dawiddrzala** [comment]
this comment is applicable to notify by anybody as well, making the ddos atack not possible as you need to increase the total rewards given to the users, it is part of the gauge code it is not relevant to the voter

**Comment by 0xklapouchy** [comment]
Escalate.

Severity should be `Low`.

In order to perform this attack, the user needs to provide additional funds, as there is a `require(amount > _left);` requirement.

This implies two things: dilution can only happen when the remaining time is now less than `DURATION / 2`. If the remaining time is more than `DURATION / 2`, the rewards will increase.

Let’s now consider two scenarios, one valid, but I don’t see it as Medium:

**Most valid of them all:**

- #92

  In the `92` scenario, additional rewards are added `201 USDC`. All users within that gauge who remain in it until the `periodFinish` will earn more from staking. Since these rewards are additional and not FLOW tokens, this is a gain for all users. There is no description of how these additional rewards should be distributed and in what intervals. This should be considered a benefit for the users, not dilution.

**Most invalid of them all:**

- #210

  It indicates calling the `notifyRewardAmount()` function every hour, which will lead to an increase in the rewards rate, not dilution. As I mentioned before, only calling `notifyRewardAmount()` after `DURATION / 2` has passed will lead to dilution of remaining rewards, but not drastically, as it is described. Each time the caller needs to provide at least the required amount (`require(amount > _left);`), the same amount as the remaining amount.

  All issues indicating calling `notifyRewardAmount()` periodically with a dust amount are invalid, and should be removed from duplicates.

  The only possible way to call `notifyRewardAmount()` with a dust amount is when the remaining rewards are a dust amount, so dilution will occur on that dust amount of rewards, which is classified as Low. In any other scenario, to dilute the rewards, any user calling `notifyRewardAmount()` needs to provide a non-small amount of tokens as rewards.


Additional note:
The `notifyRewardAmount()` function needs to be permissionless, as this is the idea behind this contract: all whitelisted tokens can be rewards and can be added by anyone, so this is by design.

**Comment by sherlock-admin3** [comment]
> Escalate.
> 
> Severity should be `Low`.
> 
> In order to perform this attack, the user needs to provide additional funds, as there is a `require(amount > _left);` requirement.
> 
> This implies two things: dilution can only happen when the remaining time is now less than `DURATION / 2`. If the remaining time is more than `DURATION / 2`, the rewards will increase.
> 
> Let’s now consider two scenarios, one valid, but I don’t see it as Medium:
> 
> **Most valid of them all:**
> 
> - #92
> 
>   In the `92` scenario, additional rewards are added `201 USDC`. All users within that gauge who remain in it until the `periodFinish` will earn more from staking. Since these rewards are additional and not FLOW tokens, this is a gain for all users. There is no description of how these additional rewards should be distributed and in what intervals. This should be considered a benefit for the users, not dilution.
> 
> **Most invalid of them all:**
> 
> - #210
> 
>   It indicates calling the `notifyRewardAmount()` function every hour, which will lead to an increase in the rewards rate, not dilution. As I mentioned before, only calling `notifyRewardAmount()` after `DURATION / 2` has passed will lead to dilution of remaining rewards, but not drastically, as it is described. Each time the caller needs to provide at least the required amount (`require(amount > _left);`), the same amount as the remaining amount.
> 
>   All issues indicating calling `notifyRewardAmount()` periodically with a dust amount are invalid, and should be removed from duplicates.
> 
>   The only possible way to call `notifyRewardAmount()` with a dust amount is when the remaining rewards are a dust amount, so dilution will occur on that dust amount of rewards, which is classified as Low. In any other scenario, to dilute the rewards, any user calling `notifyRewardAmount()` needs to provide a non-small amount of tokens as rewards.
> 
> 
> Additional note:
> The `notifyRewardAmount()` function needs to be permissionless, as this is the idea behind this contract: all whitelisted tokens can be rewards and can be added by anyone, so this is by design.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
I agree with @0xklapouchy escalation. 

Rewards cannot be diluted because the user will have to provide more reward amount than there is because of this check:

```solidity
require(amount > _left);
```

From an economic point of view, no one would do this griefing attack to dilute the rewards. It makes no economic logic. The user would lose far more than he would gain anything. 

Even if there is such a user, the issue becomes at most Low severity because of the resources the attacker has to spend. In addition, all who have mentioned that this can be done with "dust amount" are invalid because of the check.

Planning to accept the escalation and invalidate the issue.

**Comment by nevillehuang** [comment]
@cvetanovv 
Agree, with the second portion of the reward notification, within the [`else` block, where current timestamp has not exceed or equal to periodFinish](https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/GaugeV4.sol#L579-L588). However, if we consider the `if` block, wouldn't this issue be applicable? i.e there is no `require(amount > _left); ` check, wouldn't the dilution be possible?

**Comment by cvetanovv** [comment]
> @cvetanovv Agree, with the second portion of the reward notification, within the [`else` block, where current timestamp has not exceed or equal to periodFinish](https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/GaugeV4.sol#L579-L588). However, if we consider the `if` block, wouldn't this issue be applicable? i.e there is no `require(amount > _left); ` check, wouldn't the dilution be possible?


If we enter the if statement, it means that the reward period has finished.

**Comment by nevillehuang** [comment]
@cvetanovv You are correct, my mistake, in that case, this issue should be closed and the escalation can be accepted, unless an economically viable attack path is presented/PoCed

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xklapouchy](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/259/#issuecomment-2286635663): accepted
