### ISSUE TITLE
Honour - Malicious actor can dos exercise of oToken if oToken guage is not registered on voter

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#419]
Honour

High

# Malicious actor can dos exercise of oToken if oToken guage is not registered on voter

## Summary

If oToken gauge is not registered on voter, as is the case for oFlow-V4, anyone can reset the gauge via updateGuage to the gauge "registered" on voter. Effectively DOSing exercises.

## Vulnerability Detail

As a result of the V4 upgrade the oFlow token no longer uses a regular gauge and instead uses a GasToken(eg weth) `RewardsDistributor` to distribute payment rewards (from exercising oFlow) to veLP holders based on voting power. `RewardsDistributorV2` can only distribute one reward token ,this means that the gauge (which is actually a `ProxyGauge` wrapping a `RewardsDistributor`) used by oFlow will be different from the gauge registered on voter for the FLOW/GASTOKEN pair as illustrated below.
![image](https://github.com/user-attachments/assets/3f787379-c81e-4df7-80a7-500762945c5d)

## Impact

Anyone can DOS oFlow exercises by resetting the gauge after actual gauge has been set by admin.

## Code Snippet

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L412-L416

## Tool used

Manual Review

## Recommendation

updateGauge should have access control.

Duplicate of #39

**Comment by Honour-d-dev** [comment]
Escalate
This issue is not the same as #39

**Edit :** This escalation was opened before #39 was deemed valid. I'm still leaving it because i believe there are differences in terms of **impact** and **fix** that suggests that this issue should be above medium severity, whether it should still be considered a duplicate of #39 is still an open discussion too.

#39  focuses on cases where there's no registered gauge on voter for the pair as a result any user can call `updateGauge` and reset the gauge to the **address(0)** , this issue does not mention resetting to address(0) , hence why the recommendation differs from #39 and applying #39's recommendation does not fix this issue .

This issue references the underlying change in the protocol's architecture following the V4 upgrade and the introduction of the proxyGauge/rewardsDistributor.

In V3 the core pool FLOW/GASTOKEN (i.e. FLOW/ETH if mainnet) uses a regular gauge to distribute rewards and oFLOW to stakers.

In V4 the core pool no longer uses a regular gauge but a `RewardsDistributor` wrapped by a `ProxyGauge` (for compatibility). This introduces several implications ,the one relevant here is 
- RewardsDistributor's can only distribute one token as rewards (unlike a gauge that can distribute multiple) , However stakers of the core pool Lp (VeLPs) earn multiple tokens (FLOW emissions , GasToken from oFLOW exercises etc) ,this implies that the core pool is actually connected to more than one rewardsDistributor ,as illustrated by the diagram i provided and this diagram was also confirmed by the protocol team in PT to be accurate.

![image](https://github.com/user-attachments/assets/51999c25-a714-45c8-aea5-1f970643657a)

From the diagram we see that the rewardsDistributor registered to the core pool in the Voter is different from the rewardsDistributor attached to oFLOW  (the option token for the core pool) .

The issue #419 explains is that `updateGauge` can be used to set the oFLOW gauge (which is now a rewardsDistributor wrapped by a proxyGauge) to the one registered in the Voter, however the oFlow token is incompatible with it because of the mismatch in tokens (oFLOW rewards is GasToken collected from oFLOW exercises , while the rewardsDistributor on Voter expects FLOW as reward and reverts otherwise) which means oFLOW exercises are now impossible. As explained by the impact on this issue:
>Impact
Anyone can DOS oFlow exercises by resetting the gauge after actual gauge has been set by admin.

And the recommended mitigation is to access control the `updateGauge` function because checking for address(0) won't fix

**Comment by sherlock-admin3** [comment]
> Escalate
> This issue is not the same as #39
> 
> **Edit :** This escalation was opened before #39 was deemed valid. I'm still leaving it because i believe there are differences in terms of **impact** and **fix** that suggests that this issue should be above medium severity, whether it should still be considered a duplicate of #39 is still an open discussion too.
> 
> #39  focuses on cases where there's no registered gauge on voter for the pair as a result any user can call `updateGauge` and reset the gauge to the **address(0)** , this issue does not mention resetting to address(0) , hence why the recommendation differs from #39 and applying #39's recommendation does not fix this issue .
> 
> This issue references the underlying change in the protocol's architecture following the V4 upgrade and the introduction of the proxyGauge/rewardsDistributor.
> 
> In V3 the core pool FLOW/GASTOKEN (i.e. FLOW/ETH if mainnet) uses a regular gauge to distribute rewards and oFLOW to stakers.
> 
> In V4 the core pool no longer uses a regular gauge but a `RewardsDistributor` wrapped by a `ProxyGauge` (for compatibility). This introduces several implications ,the one relevant here is 
> - RewardsDistributor's can only distribute one token as rewards (unlike a gauge that can distribute multiple) , However stakers of the core pool Lp (VeLPs) earn multiple tokens (FLOW emissions , GasToken from oFLOW exercises etc) ,this implies that the core pool is actually connected to more than one rewardsDistributor ,as illustrated by the diagram i provided and this diagram was also confirmed by the protocol team in PT to be accurate.
> 
> ![image](https://github.com/user-attachments/assets/51999c25-a714-45c8-aea5-1f970643657a)
> 
> From the diagram we see that the rewardsDistributor registered to the core pool in the Voter is different from the rewardsDistributor attached to oFLOW  (the option token for the core pool) .
> 
> The issue #419 explains is that `updateGauge` can be used to set the oFLOW gauge (which is now a rewardsDistributor wrapped by a proxyGauge) to the one registered in the Voter, however the oFlow token is incompatible with it because of the mismatch in tokens (oFLOW rewards is GasToken collected from oFLOW exercises , while the rewardsDistributor on Voter expects FLOW as reward and reverts otherwise) which means oFLOW exercises are now impossible. As explained by the impact on this issue:
> >Impact
> Anyone can DOS oFlow exercises by resetting the gauge after actual gauge has been set by admin.
> 
> And the recommended mitigation is to access control the `updateGauge` function because checking for address(0) won't fix

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
Duplicate of #39, same root cause of a lack of permission within `updateGauge`, should be duplicated accordingly, as per recommended by the watson and stated in the recommendations. So I believe escalation should be rejected

**Comment by Honour-d-dev** [comment]
#39 is about lack of address(0) check not lack of permission and as i mentioned is not a fix for this.
Also #39 is a medium ,but the impact here is actually a High. A malicious actor can prevent oFLOW from being exercisable indefinitely, and it's not because there's no registered gauge (for the core pool) on voter but because the gauge on voter is not compatible with the gauge used by oFLOW

**Comment by Honour-d-dev** [comment]
My point is if this issue should still be classified as a duplicate of #39 (as they both reference the same area of code) then the impact should be high, no? based on duplication rules

**Comment by cvetanovv** [comment]
@Honour-d-dev, you are right that the higher severity is taken because of the duplication rule. I also agree that this issue should remain a duplicate of #39. The root cause of both issues is the lack of access control on `updateGauge()`.

However, both are invalid because calling the `updateGauge()` function has no impact. 

You can see this comment from the sponsor - https://discord.com/channels/812037309376495636/1272963626923200543/1273159269939675187

Planning to reject the escalation and leave the issue as is.

**Comment by Honour-d-dev** [comment]
@cvetanovv
There's a misunderstanding here and this is because of the way #39 describes the issue.
The sponsor's comment -
>Only gauge that is going to be used is the one register in voter
So there is no impact of calling update gauge
So no ddos
You can see how it is deployed in the deployment script

is actually true for other oTokens except for oFLOW (you can check the diagram in this report, which was also confirmed by sponsor). The difference is that if we check the deployment script as suggested in the comment [see here](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/script/Deployment.s.sol#L119C9-L128C11), there are 2 `RewardsDistributors` one to distribute FLOW and one to distribute ETH.
Bearing in mind that `RewardsDistributors` can only distribute one token and revert otherwise.
The gauge registered for the core pool (FLOW/ETH) on the voter will be the [`rewardsDistributorFlow`](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/script/Deployment.s.sol#L125) because the minter distributes FLOW.
The gauge to be used by oFLOW ,however, will be the [`rewardsDistributorWETH`](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/script/Deployment.s.sol#L120), no?
as oFLOW will send WETH from exercising oFLOW to it's gauge. Now if this gauge is indeed the one on voter (`rewardsDistributorFlow`) the exercising fails because `rewardsDistributorFlow` doesn't accept WETH

It's important to note that the rewardsDistributors are not called directly, but via a `ProxyGauge`  because the `notifyRewardAmount` function on rewardsDistributor has different signature, its the proxyGauge that actually reverts [here](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/ProxyGauge.sol#L34C4-L36C29) (_`flow` used here is actually just the distribution token not necessarily FLOW_)

Due to sponsor comment #39 may actually be invalid, but hopefully this completely explains the point.

**Comment by Honour-d-dev** [comment]
Here's a POC test file,  you can run the test `test_updateGaugeDOS()` , you can also confirm the setup/deployment this uses 2 `rewardsDistributors` just like in deployment script.
 

```solidity
pragma solidity 0.8.13;

import "./BaseTest.sol";
import "forge-std/console2.sol";
import "contracts/RewardsDistributorV2.sol";
import "contracts/GaugeV4.sol";
import "contracts/factories/GaugeFactoryV4.sol";
import "contracts/factories/ProxyGaugeFactory.sol";
import "contracts/ProxyGauge.sol";

contract Tests is BaseTest {
    VotingEscrow votingEscrow;
    Pair flowWethPair;
    RewardsDistributorV2 rewardsDistributorFlow;
    RewardsDistributorV2 rewardsDistributorWETH;
    Voter voter;
    Minter minter;
    GaugeV4 gauge;
    GaugeFactoryV4 gaugeFactory;
    ProxyGaugeFactory proxyGaugeFactory;
    ProxyGauge proxyGaugeFlow;
    ProxyGauge proxyGaugeWeth;
    BribeFactory bribeFactory;
    address alice = makeAddr("alice");
    address bob = makeAddr("bob");
    address candy = makeAddr("candy");

    function setUp() public {
        deployOwners();
        deployCoins();
        factory = new PairFactory();
        router = new Router(address(factory), address(WETH));
        gaugeFactory = new GaugeFactoryV4();
        proxyGaugeFactory = new ProxyGaugeFactory(address(FLOW));

        gaugePlugin = new GaugePlugin(address(FLOW), address(WETH), address(owner));
        bribeFactory = new BribeFactory();

        deployAndLpUsers(); //deploy main pool (flow/weth) ,VotingEscrow and add LP

        //Following the Deployment script
        voter = new Voter(
            address(votingEscrow),
            address(factory),
            address(gaugeFactory), //factory 0
            address(bribeFactory),
            address(gaugePlugin)
        );

        voter.addFactory(address(factory), address(proxyGaugeFactory)); //factory 1

        rewardsDistributorFlow = new RewardsDistributorV2(address(votingEscrow), address(FLOW));
        rewardsDistributorWETH = new RewardsDistributorV2(address(votingEscrow), address(WETH));

        minter = new Minter(address(voter), address(votingEscrow), address(rewardsDistributorFlow));
        minter.addRewardsDistributor(address(rewardsDistributorWETH));

        rewardsDistributorFlow.setDepositor(address(minter));
        rewardsDistributorWETH.setDepositor(address(minter));

        FLOW.setMinter(address(minter));
        votingEscrow.setTeam(address(owner));
        minter.setTeam(address(owner));
        factory.transferOwnership(address(owner));

        oFlowV4 = new OptionTokenV4(
            "Option to buy FLOW",
            "oFLOW",
            address(owner),
            address(FLOW),
            address(owner),
            address(voter),
            address(router),
            true, //exerciseLp is no longer an option on the oFlowV4
            false,
            false,
            0
        );

        factory.setVoter(address(voter));
        votingEscrow.setVoter(address(voter));
        flowWethPair.setVoter();

        proxyGaugeFactory.deployGauge(address(rewardsDistributorFlow), address(flowWethPair), ""); //setting up the proxy gauge before calling voter
        voter.createGauge(address(flowWethPair), 1); //using the proxy gauge factory , we attach the proxyGauge(rewardsDistributorFlow) to the core pool(flowWethPair)
    }

    function test_updateGaugeDOS() public {
        //We set the pool and payment token of oFLOW. Here the gauge will be set to the one in voter
        oFlowV4.setPairAndPaymentToken(flowWethPair, address(WETH));

        //assert that the gauge is actually set to the registered pool gauge on voter.
        //which is a ProxyGauge wrapper over the rewardsDistributorFlow
        assert(oFlowV4.gauge() == voter.gauges(address(flowWethPair))); //proxyGauge(rewardsDistributorFlow)

        //deploy the gauge to be used by oFLOW. Also a ProxyGauge wrapper over the rewardsDistributorWETH
        ProxyGauge wethProxyGauge = new ProxyGauge(address(WETH), address(rewardsDistributorWETH), ""); //proxyGauge(rewardsDistributorWETH)

        //Now we have to manually set the oFLOW gauge to wethProxyGauge. everything's good ✅
        oFlowV4.setGauge(address(wethProxyGauge));

        //Alice gets some oFLOW 
        FLOW.approve(address(oFlowV4), 200e18);
        oFlowV4.mint(alice, 200e18);

        //Bob resets the gauge before alice exercises
        vm.prank(bob);
        oFlowV4.updateGauge();

        vm.startPrank(alice);
        WETH.approve(address(oFlowV4), 200e18);
        //The exercise reverts
        vm.expectRevert();
        oFlowV4.exercise(200e18, type(uint256).max, alice, block.timestamp);
        vm.stopPrank();
    }

    function deployAndLpUsers() public {
        address[] memory users = new address[](4);
        uint256[] memory amounts = new uint256[](4);
        users[0] = address(owner);
        users[1] = alice;
        users[2] = bob;
        users[3] = candy;
        amounts[0] = 1000e18;
        amounts[1] = 1000e18;
        amounts[2] = 1000e18;
        amounts[3] = 1000e18;
        mintFlow(users, amounts);
        mintWETH(users, amounts);

        vm.startPrank(address(owner));
        FLOW.approve(address(router), 300e18);
        WETH.approve(address(router), 300e18);
        router.addLiquidity(address(FLOW), address(WETH), false, 300e18, 300e18, 0, 0, address(owner), block.timestamp);
        vm.stopPrank();

        flowWethPair = Pair(factory.getPair(address(FLOW), address(WETH), false));
        votingEscrow = new VotingEscrow(address(FLOW), address(flowWethPair), address(new VeArtProxy()), address(owner));

        //Adding observations so price lookup works, oFlow needs 4 observation points
        vm.warp(block.timestamp + 1801);
        flowWethPair.sync();
        vm.warp(block.timestamp + 1801);
        flowWethPair.sync();
        vm.warp(block.timestamp + 1801);
        flowWethPair.sync();
        vm.warp(block.timestamp + 1801);
        flowWethPair.sync();

    }
```

**Comment by cvetanovv** [comment]
@nevillehuang What do you think of the recent comments? Seems like a valid attack vector, and the PoC test works.

**Comment by nevillehuang** [comment]
@cvetanovv Same root cause as #39, that is lack of access control in updateGauge and the gauge must not have been listed on voter based on code comments I believe both this issue and #39 can be valid. However, there is conflicting arguments because sponsor states otherwise in the public discord thread as well as setGauge being an admin only functionality. The escalation should be rejected regardless given the root cause is the same and it is suggesting a deduplication, but the validity should be rediscussed on the primary issue. This issue is simply giving a very specific example of the general issue at hand.

> If oToken gauge is not registered on voter, as is the case for oFlow-V4, anyone can reset the gauge via updateGuage to the gauge "registered" on voter. Effectively DOSing exercises.

**Comment by Honour-d-dev** [comment]
@nevillehuang 
>the gauge must not have been listed on voter based on code comments

The core pool has a registered gauge on voter, it's just incompatible with oFLOW. That's what this line is meant to show
```solidity
//assert that the gauge is actually set to the registered pool gauge on voter.
        //which is a ProxyGauge wrapper over the rewardsDistributorFlow
        assert(oFlowV4.gauge() == voter.gauges(address(flowWethPair)));
```
> However, there is conflicting arguments because sponsor states otherwise

sponsor is actually right , all pools can be expected to have gauges on voter

>>If oToken gauge is not registered on voter, as is the case for oFlow-V4, anyone can reset the gauge via updateGuage to the gauge "registered" on voter. Effectively DOSing exercises.

What i was implying here is that the gauge used by oFLOW is not on voter ,however the core pool does have a registered gauge on voter. This is why sponsor disproved #39 because it claims the pair may not have a registered gauge.
>The escalation should be rejected regardless given the root cause is the same and it is suggesting a deduplication

This escalation is claiming this issue to be different from #39 (as #39 was considered invalid  at the time based on its claims - which sponsor disproved) and also that that the severity is actually high

**Comment by nevillehuang** [comment]
@Honour-d-dev Your discussion with sponsor is private, so it is not confirmed to me that this is their intended configuration. Also the sponsor said **only** gauges that are created in voter is supposed to be used, so not sure why yours here is a special case given the configuration is not confirmed publicly even if ur arguments is possible.

I acknowledge the possibility of validity of this issue and #39 because there are conflicting statements, but this issue shouldn’t be treated differently because of an unconfirmed configuration by the protocol.

**Comment by Honour-d-dev** [comment]
>Also the sponsor said only gauges that are created in voter is supposed to be used, so not sure why yours here is a special case given the configuration is not confirmed publicly even if ur arguments is possible.

As i've stated sponsor is correct but there's a caveat on only the core pool because only the core pool won't use a regular gauge, see some public sponsor comment's that implies this configuration (which sponsor also acknowledge in escalation screen shot)
https://discord.com/channels/812037309376495636/1257350045976760404/1261687297011748925
>Thats why we use a proxy gauge for veNFT with the contract that does the work of a gauge being the rewardsDistributer2.sol

https://discord.com/channels/812037309376495636/1261261698246119445/1261263893938962464
>So rewards distribution specifically for veNFT holders is totally changed. 
rewards distributer (does stuff related specifically related to the veNFT  rewards its a new contract).
>
>Rewards for every other pair (gauge contract) are not changed.

For more context, veNFT is the token for staking core pool LP, so veNFT are just core pool LPers and their rewards distribution configuration is different.

**Comment by dawiddrzala** [comment]
from protocol point on view there is no way, that gauge is not going to be registered in the voter, the setGuage method is leftover from old version not going to be used anymore

**Comment by Honour-d-dev** [comment]
@dawiddrzala can you please check the POC i provided ,this report does not claim that a gauge is not registered on voter (that's #39 ).
The argument i'm making here is that gauge for core pool (FLOW/ETH) and the gauge for oFlowV4 are going to different based on V4 design ,because core pool is going to use rewardsDistributor/ProxyGauge as **dunks411** mentioned in PT and in public channel 
https://discord.com/channels/812037309376495636/1257350045976760404/1261687297011748925
>Thats why we use a proxy gauge for veNFT with the contract that does the work of a gauge being the rewardsDistributer2.sol

Again the POC shows this and follows the deployment script setup as much as possible.
And just like the deployment script, we're going to need [2 rewardsDistributors](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/script/Deployment.s.sol#L119C9-L128C11), no?

```solidity
// RewardsDistributors
        RewardsDistributorV2 rewardsDistributorWETH = new RewardsDistributorV2(
            address(votingEscrow),
            WETH
        );

        RewardsDistributorV2 rewardsDistributorFlow = new RewardsDistributorV2(
            address(votingEscrow),
            address(flow)
        );
```

A rewardsDistributor can only distribute one token by design, so the one on Voter is already set to distribute FLOW to veLP(veNFT), and the one on oFlowV4 will have to be set to distribute ETH (the payment token).

From the POC you can see that `updateGauge` resets oFlowV4 gauge to the **one on Voter** (this is the important point , not to address(0)) but since the one on voter only accepts FLOW exercising reverts.

I provided this diagram to visualize this better, and you confirmed this to be correct in PT
![image](https://github.com/user-attachments/assets/67e8d646-065c-449e-ae69-bcd39fb4fbd9)

This is the configuration that fits in perfectly with the current deployment setup and shows how the 2 rewardsDistributors will be used

**Comment by dawiddrzala** [comment]
your poc is not correct you forget to setup oFlow.setRewardsAddress(NEW_REWARDS_DISTRIBUTOR_WETH) that is the reason of revert, all of that is setup in our example deployment script, so there is no ddos possible. ( you can update your poc based on the deployment scripts to see it )

**Comment by Honour-d-dev** [comment]
Ok i see what i missed ,even though the configuration is correct the rewardsDistributorWETH will not be set as `gauge` on oFlowV4 but as the `rewardsAddress` and the rewardsAddress has precedence over the gauge when rewards are being sent.
So the gauge on oFlowV4 don't matter as long as the rewardsAddress is set, it's like a fallback.

**Comment by Honour-d-dev** [comment]
@cvetanovv  i think this has been resolved, sorry for wasting everyone's time.

**Comment by cvetanovv** [comment]
We agreed that it is an invalid issue, and I will reject the escalation and leave the issue as is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Duplicate of #39

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Honour-d-dev](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/419/#issuecomment-2285033333): rejected
