### ISSUE TITLE
Honour - GuageV4 doesn't properly integrate/distribute oTokens

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#461]
Honour

High

# GuageV4 doesn't properly integrate/distribute oTokens

## Summary

GaugeV4 will not distribute oToken as rewards even if the pair has an oToken that has been added to the gauge. 

## Vulnerability Detail

GaugeV4 is expected to have external oToken support, meaning unlike a regular Gauge, GaugeV4 should be able to distribute oToken rewards(besides oFlow) to stakers i.e. pair BOB/USDC  with oToken (oBOB), oBOB would be distributed to stakers in place of BOB.
It's worth noting that oTokens are not deposited directly into the Gauge to be distributed as rewards, but are instead minted and distributed in place of their underlying token as is the case with FLOW -> oFLOW. However the `GaugeV4::getReward()` function does not have any functionality to distribute oTokens(besides oFLOW) to stakers, so even if a pair has an oToken that has been added to the gauge via `GaugeV4::addOToken()` function, the underlying token still gets distributed.
Based on current implementation it appears there's no further use case for oTokens besides adding them to the gauge.

## Impact

High, primary GaugeV4 functionality is it's support for external oTokens.

## Code Snippet

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/GaugeV4.sol#L281-L289

## Tool used

Manual Review

## Recommendation

Each oToken should be mapped to their underlying token.

```solidity
contract GaugeV4 is IGauge {
  
  mapping(address => address) public OToken;

  function addOToken(address _oToken, address _paymentToken) external {
    require(msg.sender == gaugeFactory, "not gauge factory");
    require(isReward[_paymentToken]);
    OToken[_paymentToken] = _oToken;

    emit OTokenAdded(_oToken);
  }

  function getReward(address account, address[] memory tokens) external lock {

    //...

    if (_reward > 0) {
      address oToken = OToken[tokens[i]];
      if (oToken != address(0) && oToken.code.length != 0) {
          try IOptionToken(oToken).mint(account, _reward){} catch {
              _safeTransfer(tokens[i], account, _reward);
          }
      } else {
          _safeTransfer(tokens[i], account, _reward);
      }
    }
    //...
  }
}
```

the same mapping should be used for FLOW -> oFLow.

Duplicate of #122

**Comment by nevillehuang** [comment]
Invalid, if another oToken is to be supported ,another gauge can be created

**Comment by Honour-d-dev** [comment]
Escalate
This issue is not a duplicate of #122 and is valid
To understand this issue it's important to understand the difference between gauge and gaugeV4.
The gauge distributes reward tokens to stakers of the lp token of it's pool. Only exception being the emissions token(FLOW), in this case it distributes oFLOW instead.
GaugeV4 is an upgrade to gauge, with the upgrade functionality being , to allow distribution of oTokens of other reward tokens not just FLOW. i.e. if pool BOB/USDC is connected to a gaugeV4 and BOB token has on option variant (oBOB) , then if oBOB is added to the gauge the gauge is now able to distribute oBOB in place of BOB (just like FLOW -> oFLOW)
![image](https://github.com/user-attachments/assets/8b080075-cf39-451a-bec9-a91bf77cb6a8)
Sponsors comment on PT confirming this functionality.

>Invalid, if another oToken is to be supported ,another gauge can be created

The whole point of upgrading from gauge to gaugeV4 is to support another oToken besides oFLOW

This issue #461 describes the fact that although the gaugeV4 contains functionality to add and remove oTokens as shown [here](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/GaugeV4.sol#L617C4-L627C6) , it does not have the functionality to properly distribute oTokens.
The reason for this is quite straight-forward , oTokens can only be minted in exchange for an equivalent amount of their regular variant so they need to be distributed in the same manner oFLOW is.

My recommendation suggests instead of just adding oTokens to an `isOToken` mapping as done [here](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/GaugeV4.sol#L619), we map oTokens to their regular variant so that it can be distributed in a similar fashion as oFLOW.

**Comment by sherlock-admin3** [comment]
> Escalate
> This issue is not a duplicate of #122 and is valid
> To understand this issue it's important to understand the difference between gauge and gaugeV4.
> The gauge distributes reward tokens to stakers of the lp token of it's pool. Only exception being the emissions token(FLOW), in this case it distributes oFLOW instead.
> GaugeV4 is an upgrade to gauge, with the upgrade functionality being , to allow distribution of oTokens of other reward tokens not just FLOW. i.e. if pool BOB/USDC is connected to a gaugeV4 and BOB token has on option variant (oBOB) , then if oBOB is added to the gauge the gauge is now able to distribute oBOB in place of BOB (just like FLOW -> oFLOW)
> ![image](https://github.com/user-attachments/assets/8b080075-cf39-451a-bec9-a91bf77cb6a8)
> Sponsors comment on PT confirming this functionality.
> 
> >Invalid, if another oToken is to be supported ,another gauge can be created
> 
> The whole point of upgrading from gauge to gaugeV4 is to support another oToken besides oFLOW
> 
> This issue #461 describes the fact that although the gaugeV4 contains functionality to add and remove oTokens as shown [here](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/GaugeV4.sol#L617C4-L627C6) , it does not have the functionality to properly distribute oTokens.
> The reason for this is quite straight-forward , oTokens can only be minted in exchange for an equivalent amount of their regular variant so they need to be distributed in the same manner oFLOW is.
> 
> My recommendation suggests instead of just adding oTokens to an `isOToken` mapping as done [here](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/GaugeV4.sol#L619), we map oTokens to their regular variant so that it can be distributed in a similar fashion as oFLOW.

You've deleted an escalation for this issue.

**Comment by nevillehuang** [comment]
@Honour-d-dev hmmm The protocol mentions they can earn other oTokens, but not the mechanism. My understanding during judging was that oTokens were only meant to be directly minted to users from gauges, but not distributed. Also wouldn’t oTokens be standard ERC20s that can be notified and distributed?

Maybe @dawiddrzala can check on our understanding.

**Comment by Honour-d-dev** [comment]
@nevillehuang
> My understanding during judging was that oTokens were only meant to be directly minted to users from gauges, but not distributed.

You're not wrong, just that minting oTokens is how they're distributed see the mint [function](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/OptionTokenV4.sol#L519) and an equal amount of the regular variant must be deposited.
That's how oFLOW is minted/distributed (they're the same thing)

**Comment by dawiddrzala** [comment]
not valid, other oTokens are just added as normal reward as they are erc20, minting path is only for our token as it is going directly from the minter.

**Comment by Honour-d-dev** [comment]
> not valid, other oTokens are just added as normal reward as they are erc20, minting path is only for our token as it is going directly from the minter.

I see.
This can be done with the regular gauge though, no?. 
That's why I concluded the functionality had to be different.

**Comment by Honour-d-dev** [comment]
Deleted the escalation as sponsor disproved.
