### ISSUE TITLE
StraawHaat - When a gauge is killed, its weight is not decreased

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-velocimeter-judging#477]
StraawHaat

High

# When a gauge is killed, its weight is not decreased

## Summary

When a gauge is killed, its weight is not decreased. This will lead to portion of the reward stuck in the contract.

## Vulnerability Detail

When a gauge is killed/paused using the `pauseGauge()` or `killGaugeTotally()` functions in the `Voter` contract, the gauge-related data is cleared out. 
However, it is possible that the killed gauge has already been voted for, and its respective vote weight has been added to the period's total vote weight:

```solidity
    function _vote(uint _tokenId, address[] memory _poolVote, uint256[] memory _weights) internal {
        _reset(_tokenId);
        uint _poolCnt = _poolVote.length;
        uint256 _weight = IVotingEscrow(_ve).balanceOfNFT(_tokenId);
        uint256 _totalVoteWeight = 0;
        uint256 _totalWeight = 0;
        uint256 _usedWeight = 0;

        for (uint i = 0; i < _poolCnt; i++) {
            _totalVoteWeight += _weights[i];
        }

        for (uint i = 0; i < _poolCnt; i++) {
            address _pool = _poolVote[i];
            address _gauge = gauges[_pool];

            if (isGauge[_gauge]) {
                require(isAlive[_gauge], "gauge already dead");
                uint256 _poolWeight = _weights[i] * _weight / _totalVoteWeight;
                require(votes[_tokenId][_pool] == 0);
                require(_poolWeight != 0);
                _updateFor(_gauge);

                poolVote[_tokenId].push(_pool);

                weights[_pool] += _poolWeight;
                votes[_tokenId][_pool] += _poolWeight;
               IBribe(external_bribes[_gauge])._deposit(uint256(_poolWeight), _tokenId);
                _usedWeight += _poolWeight;
                _totalWeight += _poolWeight;  //@audit - Killing a Gauge not update _totalWeight
                emit Voted(msg.sender, _tokenId, _poolWeight);
            }
        }
        if (_usedWeight > 0) IVotingEscrow(_ve).voting(_tokenId);
        totalWeight += uint256(_totalWeight); //@audit - Killing a Gauge not update _totalWeight
        usedWeights[_tokenId] = uint256(_usedWeight);
    }
```

Specifically, there are two problematic scenarios regarding the rewards accounting of the current and previous voting periods relative to the time a gauge is killed.

**Effects on the Current Voting Period**:
If a gauge is killed during an active voting period, it may have already received votes from users. These votes contribute to the `_totalWeight`, which is later used to compute the reward index for that period.

When the gauge is killed, its data is cleared, but its share of the rewards (based on the votes it received) remains in the contract. This portion of the reward is not redistributed to other gauges, resulting in unused rewards getting stuck in the contract.

**Effects on the Previous Voting Period**:
A gauge can be killed after a voting period has ended but before rewards have been distributed. The `_totalWeights` used to compute the reward index for that period includes the killed gauge's weight.

Since the killed gauge is no longer eligible for rewards, its share remains undistributed, and these rewards also get stuck in the contract.

## Impact

The period's total weight is not adjusted when a gauge is killed, resulting in the portion of the reward that is committed to that gauge remaining unused and getting stuck in the contract. 
## Code Snippet

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Voter.sol#L407-L429
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Voter.sol#L265-L285
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Voter.sol#L490

## Tool used

Manual Review

## Recommendation

To ensure that rewards are distributed correctly, the `_totalWeights` should be updated when a gauge is killed. This involves removing the killed gauge's weight from the total weight to ensure the remaining gauges receive the correct share of rewards.

**Comment by dawiddrzala** [comment]
this function require admin privileges so it is not valid, beside that kill is used for gauge migration so after kill we are going to create new gauge and we want for voting to stay

**Comment by nevillehuang** [comment]
Note, please consider not making an escalation for the following issues and duplicates as I will make a self escalation to avoid a long drawn out escalation on multiple different issues. For any issues relating to duplicates of this issue, please leave comments here so we can aggregate comments and reconsider validity.

As opposed to issue #107 and #384 which is not rectifiable, this issue and issue #477 is rectifiable based on the intended use case by the sponsor as mentioned [here](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/477#issuecomment-2282489490). As long as a new gauge is created subsequently, the votes should be retained for fair judgement (gauge creation is permisionless, and even if not, admin can perform it to bypass checks in `Voter.createGauge()`).  So as discussed with HoJ, this issue and duplicates will be invalidated per the following [sherlock rules](https://github.com/sherlock-protocol/sherlock-v2-docs/tree/29a019b8690eb01df3587868c4d7eac1e3459bda/audits/judging/judging#vii-list-of-issue-categories-that-are-not-considered-valid), note the line `or any other action causing loss of funds. This is not considered a valid issue.`, emphasis on the ANY.

> ii An admin action can break certain assumptions about the functioning of the code. Example: Pausing a collateral causes some users to be unfairly liquidated or any other action causing loss of funds. This is not considered a valid issue.

**Comment by nevillehuang** [comment]
Escalate as per comments above and as discussed [here](https://discord.com/channels/812037309376495636/1257350045976760404/1272478338610499626)

**Comment by sherlock-admin3** [comment]
> Escalate as per comments above and as discussed [here](https://discord.com/channels/812037309376495636/1257350045976760404/1272478338610499626)

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by rickkk137** [comment]
velocimeter

issue 120,220,265,561

the root cause is when the admin call killGauge weight won’t be updated

issue 544 talks about if users don’t use from full voting power they lose potential profit,that talks about user input validation and based on Sherlock rule this is invalid
issue 566 talks about the poke function and poke will be reverted if there is a dead gauge in the list and I think this is invalid


imo admin finally has to kill old version gauges because they want to migrate to the new version and they cannot wait for all users to reset their voting power because total weights just when users reset their voting power will be updated and there isn’t a mechanism to abstain voting power by admin and finally this causes a portion of base token would be locked

and finally all of this issues happen because of killGuage but #347 happen because of pauseGauge and I think #347 id duplicate of #107

finally #107 and its duplicates,#477 and its duplicates happen because of admin action and if u want to leave them as it is u should make #107 invalid based on sherlock’s rule

**Comment by pashap9990** [comment]
as I got when admin want to kill a gauge they want to migrate to new version gauge they immeditly replace old gauge with new gauge and in the end of every epoch poke function will be called and that update voting power its mean base token cannot stuck because voting power is for pool not for gauge ,I also have reported this issue [#347] but I think that is invalid

result of escalation #477 has impact on those issues related to active gauga number, i mean sponsor's arguement is to replace old gauge immediately with new guage after killing ,hence decrease active gauge number isn't meanigful

**Comment by rickkk137** [comment]
0xnevi result of escalation #477 has impact on those issues related to active gauga number, i mean sponsor's arguement is to replace old gauge immediately with new guage after killing ,hence decrease active gauge number isn't meanigful

**Comment by nevillehuang** [comment]
@cvetanovv Since there is no dispute for this issue, my escalation can be rejected

**Comment by cvetanovv** [comment]
Since the escalation is on the Lead Judge for a possible discussion, and there isn't one, I'll reject the escalation and leave the issue as is. There will be a two-day period until it is resolved, and whoever wants to can leave a comment if they think it's a valid issue.

**Comment by Almur100** [comment]
One pool can have only one gauge. Gauge can be killed. If the gauge is killed, then the pool's gauge address is updated to 0. So now another new gauge can be created with this pool.here the bug is when a gauge is killed, all variables are updated properly but the weight of the pool of the gauge is not updated to 0. So when a new gauge is created with this pool, the new gauge’s claimable share will be calculated based on previous gauge(killed gauge) weight + current gauge weight which is unfair. When a new epoch comes , previous weight (killed gauge weights) will not be reduced from the pool if the previous wright's tokenids does not vote for this pool. See the issue #120

**Comment by cvetanovv** [comment]
@Almur100 As I understand it, this was done so on purpose. When a gauge is killed, its weight should remain. If this is not the case, then this issue might be a Medium severity.

@dawiddrzala Can you please confirm that?

**Comment by nevillehuang** [comment]
@cvetanovv These are all admin functionalities, so they can break assumptions, which is why I can see the reason for #384 being invalid as well.

The intended use case is confirmed here by sponsor, in which case the totalWeights needs to be [retained](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/477#issuecomment-2282489490) if the intention is purely for a gauge migration, which is what makes this issue recitifiable. For issue #384, it is not rectifiable because the current epoch distribution logic will still count a paused/killed gauge as an active gauge, and even when migrated, might not meet the active gauge requirements. Similar case for killing gauges in #107, in which the `claimable` amount would be stuck forever

**Comment by cvetanovv** [comment]
Then my decision to reject the escalation remains.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [nevillehuang](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/477/#issuecomment-2283435589): rejected
