### ISSUE TITLE
bughuntoor - User will lose all their unclaimed rewards once their lock expires

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#649]
bughuntoor

High

# User will lose all their unclaimed rewards once their lock expires

## Summary
User will lose all their unclaimed rewards once their lock expires

## Vulnerability Detail
Let's look at the code of `_claim` within `RewardsDistributorV2`

```solidity
        for (uint i = 0; i < 50; i++) {
            if (week_cursor >= _last_token_time) break;

            if (week_cursor >= user_point.ts && user_epoch <= max_user_epoch) {
                user_epoch += 1;
                old_user_point = user_point;
                if (user_epoch > max_user_epoch) {
                    user_point = IVotingEscrow.Point(0,0,0,0);
                } else {
                    user_point = IVotingEscrow(ve).user_point_history(_tokenId, user_epoch);
                }
            } else {
                int128 dt = int128(int256(week_cursor - old_user_point.ts));
                uint balance_of = Math.max(uint(int256(old_user_point.bias - dt * old_user_point.slope)), 0);
                if (balance_of == 0 && user_epoch > max_user_epoch) break;
                if (balance_of != 0) {
                    to_distribute += balance_of * tokens_per_week[week_cursor] / ve_supply[week_cursor];
                }
                week_cursor += WEEK;
            }
        }
```

As we can see, it gets the latest point prior to the week to check against and based on the slope and bias calculates the reward. However, let's look at the case where the user's lock would have expired at the checkpoint we're looking against.
```solidity
                int128 dt = int128(int256(week_cursor - old_user_point.ts));
                uint balance_of = Math.max(uint(int256(old_user_point.bias - dt * old_user_point.slope)), 0);
```

As the lock would have expired, `old_user_point.bias - dt * old_user_point.slope` would return value less than 0. Keep in mind that the value is first wrapped in uint256 and then `Math.max` is performed.

So in the situation where the calculated bias would be `-1e18`, it would first be turned into `uint256.max - 1e18` and then the higher of it and 0 would be assigned to `balance_of`, which would basically mean the user's balance will be just a little under `uint256.max`

Which would then on the next line overflow and revert.

```solidity
                if (balance_of != 0) {
                    to_distribute += balance_of * tokens_per_week[week_cursor] / ve_supply[week_cursor];
                }
```

Meaning that if a user has had unclaimed rewards up to the point where their lock has expired, they'll remain permanently locked.

Note: same issue appears on 4 instances within the contract, this is simply the highest impact that could be done. 

## Impact
Loss of funds

## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributorV2.sol#L265

## Tool used

Manual Review

## Recommendation
First check which is the higher number and then turn it into `uint256`

**Comment by nevillehuang** [comment]
Note, please consider not making an escalation for the following issues and duplicates as I will make a self escalation to avoid a long drawn out escalation on multiple different issues. For any issues relating to duplicates of this issue, please leave comments here so we can aggregate comments and reconsider validity.

In my opinion, only the following issues mentioned the expiry precondition to that results in the unsafe casting leading to users not being able to claim rewards:

- #140
- #533
- #649
- #654

In my opinion, the following issues does not mention the expiry precondition but implies it, so arguably valid and I will leave valid duplicates and open for escalation disputes:
- #78 
- #299
- #417

In my opinion, the following does not mention or imply the expiry precondition and/or lack concrete numerical examples/PoCs, or mentioned only third party protocol impact, which is OOS
- #88 (Did not mention expiry precondition, no example numerical/coded PoC)
- #96 (Did not mention expiry precondition, no example numerical/coded PoC)
- #166 (Did not mention expiry precondition, no example numerical/coded PoC, mentions OOS third party integration and future upgrades)
- #169 (Did not mention expiry precondition, no example numerical/coded PoC, mentions OOS third party integration and future upgrade)
- #195 (Did not mention expiry precondition, no example numerical/coded PoC, mentions OOS third party integration and future upgrade)
- #249 (Did not mention expiry precondition, no example numerical/coded PoC, mentions OOS third party integration and future upgrade)
- #281 (Did not mention expiry precondition, no example numerical/coded PoC)
- #322 (Good example, but did not mention expiry precondition)
- #332 (The described impact is wrong for this issue)
- #337 (Did not mention expiry precondition, no example numerical/coded PoC, mentions OOS third party integration and future upgrade)
- #386 (good example, but no protocol specific impact described. This is essentially stating an issue but not stating how it will impact the protocol
)
- #392 (Did not mention expiry precondition, no example numerical/coded PoC)
- #400 (Did not mention expiry precondition, no example numerical/coded PoC, mentions OOS third party integration and future upgrade)
- #433 (No impact described)
- #476 (Good example, but did not mention expiry precondition)
- #503 (Did not mention expiry precondition, no example numerical/coded PoC, mentions OOS third party integration and future upgrade)
- #527 (Did not mention expiry precondition, no example numerical/coded PoC)
- #578 (Did not mention expiry precondition, no example numerical/coded PoC, mentions OOS third party integration and future upgrade)
- #594 (Good example, but did not mention expiry precondition)
- #596 (Did not mention expiry precondition, no example numerical/coded PoC)
- #617 (Did not mention expiry precondition, no example numerical/coded PoC, mentions OOS third party integration and future upgrade)
- #635 (Did not mention expiry precondition, no example numerical/coded PoC, mentions OOS third party integration and future upgrade)
- #652 (Did not mention expiry precondition, no example numerical/coded PoC, no clear impact mentioned)
- #653 (Did not mention expiry precondition, no example numerical/coded PoC)

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Velocimeter/v4-contracts/pull/17

**Comment by nevillehuang** [comment]
Escalate as per comments above and as discussed [here](https://discord.com/channels/812037309376495636/1257350045976760404/1272478338610499626)

**Comment by sherlock-admin3** [comment]
> Escalate as per comments above and as discussed [here](https://discord.com/channels/812037309376495636/1257350045976760404/1272478338610499626)

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by armormadeofwoe** [comment]
@nevillehuang  
Greetings and good luck with judging all those issues,  

Apart from #533, #649, all other reports have mentioned an invalid or low-severity impact such as:  
a) incorrect/unfair reward distribution- invalid, the function will always revert due to overflow, no distribution takes place  
b) incorrect return value on a view function - low as per your [comment on discord](https://discord.com/channels/812037309376495636/1257350045976760404/1272478338610499626)  

#140 - mentions that rewards would be unfairly distributed, no mention of revert  
#654 - mentions revert in `claim` due to insufficient balance, not due to integer overflow  
#78 - mentions revert in `claim` due to insufficient balance, not due to integer overflow  
#299 - considers only the incorrectness of the return value of `ve_for_at`, no mention of `claim` reverting due to overflow  
#417 - no mention of revert during claim, considers the function passing  

The impacts of 533 and 649 revolve around permanently locked funds, hence why they should not be paired with the list above. At the same time the root-cause of all 7 issues is the same, therefore splitting them into 2 separate trees does not make sense either. 
 
Leaving the rest to you.

**Comment by Audinarey** [comment]
@nevillehuang I believe you have thoroughly reviewed #654 and that your current claims are correct 

it explicitly mentions in the summary section that

> ... In the RewardDistributor contract, the balance of a token at specific time can lead to silent overflow due to unsafe casting

also the rightly noted expiry condition
> ...(considering that the user could have locked for less than 50 weeks and he is claiming his rewards for the first time after 50 weeks) since the point he lock his lp

**Comment by web3-master** [comment]
@nevillehuang 
Hello.
Would you please review my following opinion about issue #96?

My issue #96 stated the expiry precondition condition as when pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts))) is negative which is equal to the expiry precondition.
And the issue stated _claim function has underflow error which is not view function, so it has medium severity.
For POC, as it is so clear, separate POC is not needed.

Thanks in advance.

**Comment by chinmay-farkya** [comment]
Hey @nevillehuang I'd like to point out that user DOS while claiming rewards is one impact of this bug.

But my issue #594 points out another impact of this which is not dependent upon "expiry precondition"

My issue points out the issue within the checkpoint_total_Supply where the veSupply is calculated incorrectly, so it is not related to "user claiming rewards gets DOS'ed" and so it does not require a mention of the expiry precondition. 

If you look at #594 again, it describes veSupply will get recorded as a huge positive number, and this value will then be used while distributing rewards inside _claim, where the "toDistribute" variable will be recorded as way smaller because its divided by veSupply. See [here](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L211).

This is a separate impact from the one described in the main issue #649 , but it is indeed a valid impact. This will happen under normal conditions for every user and the system as a whole, regardless of the user position being expired or not.

**Comment by 0xklapouchy** [comment]
Escalate.

The issue is only within the `RewardsDistributorV2.ve_for_at()` function. It is a view function, so you can even consider this `Low`.

However, there is no issue within the `_claim()`, `_claimable()`, or `_checkpoint_total_supply()` functions.

The code indicates that there is a possibility of unsafe casting, but it will never happen as `int256(old_user_point.bias - dt * old_user_point.slope)` will always be `>= 0`. The code prevents other values.

The reason this will be `>= 0`, is that for the first `week_cursor` where the user has an expired tokenId is that `balance_of == 0`, but also `user_epoch > max_user_epoch`, which will break the `for` loop.

`if (balance_of == 0 && user_epoch > max_user_epoch) break;`

There is a reason why none of the issues above have a working PoC to confirm issue withing the `_claim()` function.

A working PoC is needed to confirm this issue for it to be valid.

**Comment by sherlock-admin3** [comment]
> Escalate.
> 
> The issue is only within the `RewardsDistributorV2.ve_for_at()` function. It is a view function, so you can even consider this `Low`.
> 
> However, there is no issue within the `_claim()`, `_claimable()`, or `_checkpoint_total_supply()` functions.
> 
> The code indicates that there is a possibility of unsafe casting, but it will never happen as `int256(old_user_point.bias - dt * old_user_point.slope)` will always be `>= 0`. The code prevents other values.
> 
> The reason this will be `>= 0`, is that for the first `week_cursor` where the user has an expired tokenId is that `balance_of == 0`, but also `user_epoch > max_user_epoch`, which will break the `for` loop.
> 
> `if (balance_of == 0 && user_epoch > max_user_epoch) break;`
> 
> There is a reason why none of the issues above have a working PoC to confirm issue withing the `_claim()` function.
> 
> A working PoC is needed to confirm this issue for it to be valid.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 0xklapouchy** [comment]
@nevillehuang 
This issue itself is invalid, only issues for ve_for_at() are valid, but can be `Low` as it is just view function.

**Comment by goheesheng** [comment]
> @nevillehuang Greetings and good luck with judging all those issues,
> 
> Apart from #533, #649, all other reports have mentioned an invalid or low-severity impact such as: a) incorrect/unfair reward distribution- invalid, the function will always revert due to overflow, no distribution takes place b) incorrect return value on a view function - low as per your [comment on discord](https://discord.com/channels/812037309376495636/1257350045976760404/1272478338610499626)
> 
> #140 - mentions that rewards would be unfairly distributed, no mention of revert #654 - mentions revert in `claim` due to insufficient balance, not due to integer overflow #78 - mentions revert in `claim` due to insufficient balance, not due to integer overflow #299 - considers only the incorrectness of the return value of `ve_for_at`, no mention of `claim` reverting due to overflow #417 - no mention of revert during claim, considers the function passing
> 
> The impacts of 533 and 649 revolve around permanently locked funds, hence why they should not be paired with the list above. At the same time the root-cause of all 7 issues is the same, therefore splitting them into 2 separate trees does not make sense either.
> 
> Leaving the rest to you.

Do read my Example Scenario where include explicitly integer overflow with a PoC.

**Comment by cvetanovv** [comment]
@0xklapouchy is right with this [comment](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/649#issuecomment-2286396184). 

In the `_claim()`, `_claimable()`, and `_checkpoint_total_supply()` functions, there it's not possible to occur an overflow, and the only function that overflow can occur is `ve_for_at()`. 

But it is a `view` function, and for the issue to be valid, another function must use it.

If someone thinks an overflow can occur, he can write a PoC test.

Planning to accept the escalation and invalidate the issues.

**Comment by nevillehuang** [comment]
I agree with invalidating the issues, given users also should be aware of their NFT expiry and claim rewards accordingly and/or extend their locks before allowing expiry.

**Comment by Audinarey** [comment]
> The protocol team fixed this issue in the following PRs/commits: https://github.com/Velocimeter/v4-contracts/pull/17

@nevillehuang the protocol team has fixed the issue per [this comment](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/649#issuecomment-2283085297), why still invalidate it if they believe it is an issue. I ask while trusting your judgement

**Comment by 0xklapouchy** [comment]
@Audinarey 
We can't see what was fixed, but we can assume it indeed addressed the unsafe casting, as it is good practice to ensure safe casting.

And still, there is no possibility for that error to occur in any function other than `ve_for_at()`. If I'm wrong, you can easily prove it with a coded PoC.

Even in the Spearbit issue 5.3.6, there is a recommendation to apply the fix to other parts, not just the `veForAt()` function, even though the issue is only present in `veForAt()`.

**Comment by cvetanovv** [comment]
> > The protocol team fixed this issue in the following PRs/commits: https://github.com/Velocimeter/v4-contracts/pull/17
> 
> @nevillehuang the protocol team has fixed the issue per [this comment](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/649#issuecomment-2283085297), why still invalidate it if they believe it is an issue. I ask while trusting your judgement

Just because the protocol has add a "will fix" , label doesn't mean it has to be Medium severity. My decision to accept the escalation and invalidate the issue remains.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates 

*Note: @nevillehuang escalation was rejected because it asked to consider duplicates, while the entire issue is invalid*

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xklapouchy](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/649/#issuecomment-2286396184): accepted
- [nevillehuang](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/649/#issuecomment-2283436476): rejected

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
